#ifndef HLCD_CONFIG_H
#define HLCD_CONFIG_H



#define HLCD_CONTROL_PORT PORTD
#define HLCD_RS	PIN_5
#define HLCD_RW	PIN_6
#define HLCD_EN	PIN_7
#define HLCD_DATA_PORT	PORTB

#define HLCD_CURSOR_MODE	HLCD_CURSOR_OFF
#define HLCD_CURSOR_BLINK	HLCD_CURSOR_BLINK_OFF

#define HLCD_MODE HLCD_MODE_8_BIT

#endif
