#ifndef HLCD_CONFIG_H
#define HLCD_CONFIG_H



#define HLCD_CONTROL_PORT PORTD
#define HLCD_RS	PIN_0
#define HLCD_RW	PIN_1
#define HLCD_EN	PIN_2
#define HLCD_DATA_PORT	PORTA

#define HLCD_CURSOR_MODE	HLCD_CURSOR_OFF
#define HLCD_CURSOR_BLINK	HLCD_CURSOR_BLINK_OFF

#define HLCD_MODE HLCD_MODE_8_BIT

#endif
