#ifndef HPB_CONFIG_H
#define HPB_CONFIG_H

#define HPB_SAMPLE_TIME_MS 		5
#define HPB_NO_OF_SAMPLES_TO_CHANGE_STATE 5

#define HPB_NO_OF_BUTTONS	4
#define HPB_PORTS		{PORTC, PORTD, PORTA, PORTB}
#define HPB_PINS 		{PIN_0, PIN_7, PIN_4, PIN_3}
#define HPB_CONNECTIONS	{HPB_CONNECTION_PULLDOWN,HPB_CONNECTION_PULLDOWN, HPB_CONNECTION_PULLUP, HPB_CONNECTION_PULLUP}


#endif
//
