#ifndef MSPI_CONFIG_H_
#define MSPI_CONFIG_H_

#define MSPI_CFG_DATA_ORDER     MSPI_LSB_FIRST
#define MSPI_CFG_CLK_POLARITY   MSPI_CLK_POLARITY_IDLE_LOW
#define MSPI_CFG_CLK_PHASE      MSPI_CLK_PHASE_SAMPLE_ON_TRAILING

#define MSPI_CFG_CLK_RATE		MSPI_CLK_RATE_3
#define MSPI_CFG_SPEED_MODE		MSPI_SPEED_MODE_NORMAL

#define MSPI_CFG_DUMMY_DATA     0xAA

#endif
